services:
  - type: web
    name: hotstar-scraper
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      # Install Chrome and ChromeDriver
      apt-get update
      apt-get install -y wget gnupg unzip
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update
      apt-get install -y google-chrome-stable
      # Install ChromeDriver
      CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
      wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/$(echo $CHROME_DRIVER_VERSION)/chromedriver_linux64.zip
      unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver
    startCommand: gunicorn --bind 0.0.0.0:$PORT hotstar:app
    envVars:
      - key: PYTHONPATH
        value: .
      - key: DISPLAY
        value: :99
    disk:
      name: hotstar-disk
      mountPath: /tmp
      sizeGB: 1